function [ DD ] = FD2d4o( D,d )
% This function determines the second order derivatives of a function/field 
% that is given on a uniform grid. Note: the derivative is taken in the 
% along the rows of the data, assuming the corresponding coordinate ascends 
% when the column index decreases. 
%
%       <-- x;  x_2 > x_1
%      _ _ _ _ _ _ _ _ _ _
%     | f(x_2) ... f(x_1) |
% D = |                   |
%     :                   :

% set size of derivative matrix DD
DD = 0*D; 

% using cental differences for the "center nodes":
DD(:,  (1+2):(end-2)) =( -1/12 * D(:,  (1+4):(end-0))...
                      +    4/3 * D(:,  (1+3):(end-1))...
                      -    5/2 * D(:,  (1+2):(end-2))...
                      +    4/3 * D(:,  (1+1):(end-3))...
                      -   1/12 * D(:,  (1+0):(end-4)))./d^2;

% using forward differences for the first (smallest coordinate values) two 
% columns:
DD(:,(end-1):(end-0)) =(  15/4 * D(:,(end-1):(end-0))...
                      -   77/6 * D(:,(end-2):(end-1))...
                      +  107/6 * D(:,(end-3):(end-2))...
                      -     13 * D(:,(end-4):(end-3))...
                      +  61/12 * D(:,(end-5):(end-4))...
                      -    5/6 * D(:,(end-6):(end-5)))./d^2;
        
% using backward differences for the last (largest coordinate values) two 
% columns:
DD(:,  (1+0):  (1+1)) =(  15/4 * D(:,  (1+0):  (1+1))...
                      -   77/6 * D(:,  (1+1):  (1+2))...
                      +  107/6 * D(:,  (1+2):  (1+3))...
                      -     13 * D(:,  (1+3):  (1+4))...
                      +  61/12 * D(:,  (1+4):  (1+5))...
                      -    5/6 * D(:,  (1+5):  (1+6)))./d^2;                  

end

